spring:
  data:
    rest:
      base-path: /v1/api

    elasticsearch:
              cluster-name:
              cluster-nodes:
              properties:
                  path:
                    logs: target/elasticsearch/log
                    data: target/elasticsearch/data